// <auto-generated />
namespace BookBeat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class aspnetusertable_foriegnkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aspnetusertable_foriegnkey));
        
        string IMigrationMetadata.Id
        {
            get { return "202403260253073_aspnetusertable_foriegnkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
